name: CD


run-name: ${{ github.event.pull_request.title }}


on:
  push:
    branches: [ main ]


jobs:
  deploy-to-gae:
    permissions:
      contents: 'read'
      id-token: 'write'


    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'


    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/248506192210/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'github-actions-svc@wayman-temp-project.iam.gserviceaccount.com'


    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v1'
